/**
 * Phase 1 security invariants — static scan of the source tree.
 * Ensures no dangerous capabilities were introduced.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SCAN_DIRS = ["src", "tools"];

/** Patterns that must not appear in Phase 1 application code. */
const FORBIDDEN_PATTERNS: Array<{ name: string; pattern: RegExp }> = [
  { name: "child_process", pattern: /\bchild_process\b/ },
  { name: "exec(", pattern: /\bexec\s*\(/ },
  { name: "execSync(", pattern: /\bexecSync\s*\(/ },
  { name: "spawn(", pattern: /\bspawn\s*\(/ },
  { name: "spawnSync(", pattern: /\bspawnSync\s*\(/ },
  { name: "fork(", pattern: /\bfork\s*\(/ },
  { name: "eval(", pattern: /\beval\s*\(/ },
  { name: "Function constructor", pattern: /\bnew\s+Function\s*\(/ },
  { name: "shell:true", pattern: /shell\s*:\s*true/ },
  { name: "/bin/sh", pattern: /\/bin\/sh/ },
  { name: "cmd.exe", pattern: /cmd\.exe/i },
  { name: "powershell", pattern: /\bpowershell\b/i },
  { name: "navigator.mediaDevices", pattern: /navigator\.mediaDevices/ },
  { name: "getUserMedia", pattern: /\bgetUserMedia\b/ },
  { name: "webkitGetUserMedia", pattern: /\bwebkitGetUserMedia\b/ },
  { name: "MediaRecorder", pattern: /\bMediaRecorder\b/ },
  { name: "camera access", pattern: /\b(enumerateDevices|getDisplayMedia)\b/ },
  { name: "microphone", pattern: /\bmicrophone\b/i },
  { name: "Robot / nut.js keyboard", pattern: /\b(@nut-tree|robotjs|nut\.js)\b/i },
  { name: "net socket client", pattern: /\bfrom\s+["']node:net["']/ },
  { name: "http request", pattern: /\bfrom\s+["']node:http["']/ },
  { name: "https request", pattern: /\bfrom\s+["']node:https["']/ },
  { name: "fetch to external", pattern: /\bfetch\s*\(/ },
  { name: "axios", pattern: /\baxios\b/ },
  { name: "openai", pattern: /\bopenai\b/i },
  { name: "ollama", pattern: /\bollama\b/i },
  { name: "fs writeFile", pattern: /\bwriteFile(?:Sync)?\s*\(/ },
  { name: "fs unlink", pattern: /\bunlink(?:Sync)?\s*\(/ },
  { name: "fs rm", pattern: /\brm(?:Sync)?\s*\(/ },
  { name: "fs mkdir write", pattern: /\bappendFile(?:Sync)?\s*\(/ },
  { name: "SMS / telephony", pattern: /\b(twilio|tel:|sms:|sendSMS)\b/i },
  { name: "Gmail API", pattern: /\bgmail\b/i },
  {
    name: "Sophie repo import",
    // Forbid importing Sophie's BehaviorBrain — local SophieAPI/SophieEventBus are JARVIS-owned (Phase 12).
    pattern:
      /\b(?:import|require)\b[\s\S]{0,80}\bBehaviorBrain\b/,
  },
];

/** Files that are allowed to mention certain patterns (tests/docs scanners). */
const ALLOWLIST: Array<{ fileSubstring: string; patternNames: string[] }> = [
  {
    fileSubstring: "security-invariants.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "eval(",
      "Function constructor",
      "shell:true",
      "/bin/sh",
      "cmd.exe",
      "powershell",
      "navigator.mediaDevices",
      "getUserMedia",
      "webkitGetUserMedia",
      "MediaRecorder",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "net socket client",
      "http request",
      "https request",
      "fetch to external",
      "axios",
      "openai",
      "ollama",
      "fs writeFile",
      "fs unlink",
      "fs rm",
      "fs mkdir write",
      "SMS / telephony",
      "Gmail API",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "jarvis-core-smoke.ts",
    patternNames: ["microphone", "Sophie repo import", "openai", "ollama"],
  },
  {
    fileSubstring: "JARVIS_ARCHITECTURE.md",
    patternNames: [
      "microphone",
      "openai",
      "ollama",
      "Gmail API",
      "Sophie repo import",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
    ],
  },
  {
    fileSubstring: "jarvis-core-phase1-report.txt",
    patternNames: [
      "microphone",
      "openai",
      "ollama",
      "Gmail API",
      "Sophie repo import",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
      "camera access",
    ],
  },
  {
    fileSubstring: "JARVIS_OBSERVATION.md",
    patternNames: [
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
      "openai",
      "ollama",
      "Gmail API",
      "SMS / telephony",
      "fs writeFile",
      "fs unlink",
      "fs rm",
    ],
  },
  {
    fileSubstring: "jarvis-observation-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "eval(",
      "Function constructor",
      "shell:true",
      "/bin/sh",
      "cmd.exe",
      "powershell",
      "navigator.mediaDevices",
      "getUserMedia",
      "webkitGetUserMedia",
      "MediaRecorder",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "net socket client",
      "http request",
      "https request",
      "fetch to external",
      "axios",
      "openai",
      "ollama",
      "fs writeFile",
      "fs unlink",
      "fs rm",
      "fs mkdir write",
      "SMS / telephony",
      "Gmail API",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "jarvis-observation-smoke.ts",
    patternNames: ["microphone", "openai", "ollama"],
  },
  {
    fileSubstring: "jarvis-observation-phase2-report.txt",
    patternNames: [
      "microphone",
      "openai",
      "ollama",
      "Gmail API",
      "Sophie repo import",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
      "camera access",
      "SMS / telephony",
      "fs writeFile",
      "fs unlink",
      "fs rm",
    ],
  },
  {
    fileSubstring: "FileService.ts",
    patternNames: [
      "fs writeFile",
      "fs unlink",
      "fs rm",
      "fs mkdir write",
    ],
  },
  {
    fileSubstring: "jarvis-file-control-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "eval(",
      "Function constructor",
      "shell:true",
      "/bin/sh",
      "cmd.exe",
      "powershell",
      "navigator.mediaDevices",
      "getUserMedia",
      "webkitGetUserMedia",
      "MediaRecorder",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "net socket client",
      "http request",
      "https request",
      "fetch to external",
      "axios",
      "openai",
      "ollama",
      "fs writeFile",
      "fs unlink",
      "fs rm",
      "fs mkdir write",
      "SMS / telephony",
      "Gmail API",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "jarvis-file-control-smoke.ts",
    patternNames: [
      "fs writeFile",
      "fs unlink",
      "fs rm",
      "fs mkdir write",
      "microphone",
      "openai",
      "ollama",
    ],
  },
  {
    fileSubstring: "JARVIS_FILE_CONTROL.md",
    patternNames: [
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
      "openai",
      "ollama",
      "fs writeFile",
      "fs unlink",
      "fs rm",
      "SMS / telephony",
      "Gmail API",
    ],
  },
  {
    fileSubstring: "jarvis-file-control-phase3-report.txt",
    patternNames: [
      "microphone",
      "openai",
      "ollama",
      "Gmail API",
      "Sophie repo import",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
      "camera access",
      "SMS / telephony",
      "fs writeFile",
      "fs unlink",
      "fs rm",
    ],
  },
  {
    fileSubstring: "jarvis-application-control-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "eval(",
      "Function constructor",
      "shell:true",
      "/bin/sh",
      "cmd.exe",
      "powershell",
      "navigator.mediaDevices",
      "getUserMedia",
      "webkitGetUserMedia",
      "MediaRecorder",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "net socket client",
      "http request",
      "https request",
      "fetch to external",
      "axios",
      "openai",
      "ollama",
      "fs writeFile",
      "fs unlink",
      "fs rm",
      "fs mkdir write",
      "SMS / telephony",
      "Gmail API",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "jarvis-application-control-smoke.ts",
    patternNames: [
      "microphone",
      "openai",
      "ollama",
      "Robot / nut.js keyboard",
    ],
  },
  {
    fileSubstring: "JARVIS_APPLICATION_CONTROL.md",
    patternNames: [
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
      "openai",
      "ollama",
      "Robot / nut.js keyboard",
      "SMS / telephony",
      "Gmail API",
    ],
  },
  {
    fileSubstring: "jarvis-application-control-phase4-report.txt",
    patternNames: [
      "microphone",
      "openai",
      "ollama",
      "Gmail API",
      "Sophie repo import",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
      "camera access",
      "SMS / telephony",
      "Robot / nut.js keyboard",
    ],
  },
  {
    fileSubstring: "jarvis-macos-backend-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "eval(",
      "Function constructor",
      "shell:true",
      "/bin/sh",
      "cmd.exe",
      "powershell",
      "navigator.mediaDevices",
      "getUserMedia",
      "webkitGetUserMedia",
      "MediaRecorder",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "net socket client",
      "http request",
      "https request",
      "fetch to external",
      "axios",
      "openai",
      "ollama",
      "fs writeFile",
      "fs unlink",
      "fs rm",
      "fs mkdir write",
      "SMS / telephony",
      "Gmail API",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "jarvis-macos-application-backend-smoke.ts",
    patternNames: ["microphone", "openai", "ollama", "Robot / nut.js keyboard"],
  },
  {
    fileSubstring: "jarvis-macos-native-phase5-report.txt",
    patternNames: [
      "microphone",
      "openai",
      "ollama",
      "Gmail API",
      "Sophie repo import",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
      "camera access",
      "SMS / telephony",
      "Robot / nut.js keyboard",
    ],
  },
  {
    fileSubstring: "jarvis-screen-observation-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "eval(",
      "Function constructor",
      "shell:true",
      "/bin/sh",
      "cmd.exe",
      "powershell",
      "navigator.mediaDevices",
      "getUserMedia",
      "webkitGetUserMedia",
      "MediaRecorder",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "net socket client",
      "http request",
      "https request",
      "fetch to external",
      "axios",
      "openai",
      "ollama",
      "fs writeFile",
      "fs unlink",
      "fs rm",
      "fs mkdir write",
      "SMS / telephony",
      "Gmail API",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "jarvis-screen-observation-smoke.ts",
    patternNames: ["microphone", "openai", "ollama", "Robot / nut.js keyboard", "camera access"],
  },
  {
    fileSubstring: "JARVIS_SCREEN_OBSERVATION.md",
    patternNames: [
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
      "openai",
      "ollama",
      "Robot / nut.js keyboard",
      "MediaRecorder",
      "getUserMedia",
    ],
  },
  {
    fileSubstring: "jarvis-screen-observation-phase6-report.txt",
    patternNames: [
      "microphone",
      "openai",
      "ollama",
      "Gmail API",
      "Sophie repo import",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
      "camera access",
      "SMS / telephony",
      "Robot / nut.js keyboard",
    ],
  },
  {
    fileSubstring: "jarvis-user-activity-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "eval(",
      "Function constructor",
      "shell:true",
      "/bin/sh",
      "cmd.exe",
      "powershell",
      "navigator.mediaDevices",
      "getUserMedia",
      "webkitGetUserMedia",
      "MediaRecorder",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "net socket client",
      "http request",
      "https request",
      "fetch to external",
      "axios",
      "openai",
      "ollama",
      "SMS / telephony",
      "Gmail API",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "jarvis-user-activity-smoke.ts",
    patternNames: ["microphone", "openai", "ollama", "camera access"],
  },
  {
    fileSubstring: "JARVIS_USER_ACTIVITY.md",
    patternNames: [
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
      "openai",
      "ollama",
      "Robot / nut.js keyboard",
      "MediaRecorder",
      "getUserMedia",
    ],
  },
  {
    fileSubstring: "jarvis-user-activity-phase7-report.txt",
    patternNames: [
      "microphone",
      "openai",
      "ollama",
      "Gmail API",
      "Sophie repo import",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
      "camera access",
      "SMS / telephony",
      "Robot / nut.js keyboard",
    ],
  },
  {
    fileSubstring: "jarvis-action-execution-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "eval(",
      "Function constructor",
      "shell:true",
      "/bin/sh",
      "cmd.exe",
      "powershell",
      "navigator.mediaDevices",
      "getUserMedia",
      "webkitGetUserMedia",
      "MediaRecorder",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "net socket client",
      "http request",
      "https request",
      "fetch to external",
      "axios",
      "openai",
      "ollama",
      "SMS / telephony",
      "Gmail API",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "jarvis-action-execution-smoke.ts",
    patternNames: [
      "microphone",
      "openai",
      "ollama",
      "camera access",
      "fs writeFile",
      "fs unlink",
      "fs rm",
      "fs mkdir write",
    ],
  },
  {
    fileSubstring: "JARVIS_ACTION_EXECUTION.md",
    patternNames: [
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
      "openai",
      "ollama",
      "Robot / nut.js keyboard",
      "Function constructor",
      "shell:true",
    ],
  },
  {
    fileSubstring: "jarvis-action-execution-phase8-report.txt",
    patternNames: [
      "microphone",
      "openai",
      "ollama",
      "Gmail API",
      "Sophie repo import",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "fetch to external",
      "camera access",
      "SMS / telephony",
      "Robot / nut.js keyboard",
      "Function constructor",
      "shell:true",
    ],
  },
  {
    fileSubstring: "OllamaLLMProvider.ts",
    patternNames: ["fetch to external", "ollama", "openai"],
  },
  {
    fileSubstring: "src/ai/",
    patternNames: ["ollama", "openai", "fetch to external"],
  },
  {
    fileSubstring: "registerIntentTools.ts",
    patternNames: ["ollama"],
  },
  {
    fileSubstring: "jarvis-llm-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "eval(",
      "Function constructor",
      "shell:true",
      "/bin/sh",
      "cmd.exe",
      "powershell",
      "getUserMedia",
      "MediaRecorder",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "fetch to external",
      "openai",
      "ollama",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "jarvis-llm-smoke.ts",
    patternNames: [
      "ollama",
      "openai",
      "fetch to external",
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
    ],
  },
  {
    fileSubstring: "JARVIS_LLM.md",
    patternNames: [
      "ollama",
      "openai",
      "fetch to external",
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "Robot / nut.js keyboard",
      "Function constructor",
      "shell:true",
    ],
  },
  {
    fileSubstring: "jarvis-llm-phase9-report.txt",
    patternNames: [
      "ollama",
      "openai",
      "fetch to external",
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "Robot / nut.js keyboard",
      "Function constructor",
      "shell:true",
      "Sophie repo import",
      "Gmail API",
      "SMS / telephony",
    ],
  },
  {
    fileSubstring: "core/index.ts",
    patternNames: ["ollama"],
  },
  {
    fileSubstring: "src/runtime/",
    patternNames: ["ollama", "openai", "fetch to external", "microphone"],
  },
  {
    fileSubstring: "jarvis-runtime-smoke.ts",
    patternNames: [
      "ollama",
      "openai",
      "fetch to external",
      "microphone",
      "camera access",
      "fs writeFile",
      "fs unlink",
      "fs rm",
      "fs mkdir write",
      "child_process",
      "exec(",
      "spawn(",
    ],
  },
  {
    fileSubstring: "jarvis-runtime-security-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "eval(",
      "shell:true",
      "getUserMedia",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "fetch to external",
      "openai",
      "ollama",
      "Function constructor",
    ],
  },
  {
    fileSubstring: "jarvis-runtime-audit.ts",
    patternNames: ["microphone", "openai", "ollama", "fs writeFile"],
  },
  {
    fileSubstring: "JARVIS_RUNTIME.md",
    patternNames: [
      "ollama",
      "openai",
      "fetch to external",
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "Robot / nut.js keyboard",
      "shell:true",
    ],
  },
  {
    fileSubstring: "jarvis-runtime-phase10-report.txt",
    patternNames: [
      "ollama",
      "openai",
      "fetch to external",
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "Robot / nut.js keyboard",
      "shell:true",
      "Sophie repo import",
      "Gmail API",
      "SMS / telephony",
      "Function constructor",
    ],
  },
  {
    fileSubstring: "LLMHealth.ts",
    patternNames: ["ollama", "openai", "fetch to external"],
  },
  {
    fileSubstring: "src/context/",
    patternNames: ["microphone", "camera access", "fetch to external"],
  },
  {
    fileSubstring: "jarvis-context-security-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "eval(",
      "Function constructor",
      "shell:true",
      "/bin/sh",
      "cmd.exe",
      "powershell",
      "getUserMedia",
      "MediaRecorder",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "fetch to external",
      "openai",
      "ollama",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "jarvis-context-audit.ts",
    patternNames: [
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "fetch to external",
    ],
  },
  {
    fileSubstring: "jarvis-context-smoke.ts",
    patternNames: [
      "ollama",
      "openai",
      "fetch to external",
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
    ],
  },
  {
    fileSubstring: "JARVIS_CONTEXT.md",
    patternNames: [
      "ollama",
      "openai",
      "fetch to external",
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "Robot / nut.js keyboard",
      "Function constructor",
      "shell:true",
      "SMS / telephony",
      "Gmail API",
    ],
  },
  {
    fileSubstring: "jarvis-context-phase11-report.txt",
    patternNames: [
      "ollama",
      "openai",
      "fetch to external",
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "Robot / nut.js keyboard",
      "shell:true",
      "Sophie repo import",
      "Gmail API",
      "SMS / telephony",
      "Function constructor",
    ],
  },
  {
    fileSubstring: "src/integration/",
    patternNames: [
      "Sophie repo import",
      "microphone",
      "camera access",
      "fetch to external",
    ],
  },
  {
    fileSubstring: "jarvis-integration-security-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "eval(",
      "Function constructor",
      "shell:true",
      "/bin/sh",
      "cmd.exe",
      "powershell",
      "getUserMedia",
      "MediaRecorder",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "fetch to external",
      "openai",
      "ollama",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "integration-contract-test.ts",
    patternNames: [
      "child_process",
      "exec(",
      "spawn(",
      "shell:true",
      "microphone",
      "camera access",
      "fetch to external",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "jarvis-integration-smoke.ts",
    patternNames: [
      "ollama",
      "openai",
      "fetch to external",
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "JARVIS_SOPHIE_INTEGRATION.md",
    patternNames: [
      "ollama",
      "openai",
      "fetch to external",
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "Robot / nut.js keyboard",
      "Function constructor",
      "shell:true",
      "SMS / telephony",
      "Gmail API",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "jarvis-sophie-integration-phase12-report.txt",
    patternNames: [
      "ollama",
      "openai",
      "fetch to external",
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "eval(",
      "Robot / nut.js keyboard",
      "shell:true",
      "Sophie repo import",
      "Gmail API",
      "SMS / telephony",
      "Function constructor",
    ],
  },
  {
    fileSubstring: "JARVIS_MACOS_NATIVE.md",
    patternNames: [
      "child_process",
      "exec(",
      "spawn(",
      "shell:true",
      "microphone",
      "camera access",
      "Robot / nut.js keyboard",
      "fetch to external",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "jarvis-macos-native-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "shell:true",
      "getUserMedia",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "fetch to external",
      "axios",
    ],
  },
  {
    fileSubstring: "jarvis-macos-native-smoke.ts",
    patternNames: [
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "fetch to external",
    ],
  },
  {
    fileSubstring: "jarvis-macos-native-phase13-report.txt",
    patternNames: [
      "child_process",
      "exec(",
      "spawn(",
      "shell:true",
      "microphone",
      "camera access",
      "Robot / nut.js keyboard",
      "fetch to external",
      "Sophie repo import",
      "Gmail API",
      "SMS / telephony",
      "Function constructor",
      "eval(",
    ],
  },
  {
    fileSubstring: "JARVIS_APPLICATION_CONTROL.md",
    patternNames: ["child_process", "exec(", "spawn(", "shell:true"],
  },
  {
    fileSubstring: "JARVIS_SCREEN_OBSERVATION.md",
    patternNames: ["microphone", "camera access"],
  },
  {
    fileSubstring: "JARVIS_USER_ACTIVITY.md",
    patternNames: [
      "child_process",
      "exec(",
      "spawn(",
      "microphone",
      "camera access",
    ],
  },
  {
    fileSubstring: "JARVIS_SECURITY.md",
    patternNames: [
      "child_process",
      "exec(",
      "spawn(",
      "fork(",
      "shell:true",
      "microphone",
      "camera access",
      "Robot / nut.js keyboard",
      "fetch to external",
      "Sophie repo import",
      "Gmail API",
      "SMS / telephony",
      "eval(",
      "Function constructor",
    ],
  },
  {
    fileSubstring: "jarvis-security-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "shell:true",
      "getUserMedia",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "fetch to external",
      "axios",
    ],
  },
  {
    fileSubstring: "jarvis-security-smoke.ts",
    patternNames: [
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "fetch to external",
    ],
  },
  {
    fileSubstring: "jarvis-security-phase14-report.txt",
    patternNames: [
      "child_process",
      "exec(",
      "spawn(",
      "shell:true",
      "microphone",
      "camera access",
      "Robot / nut.js keyboard",
      "fetch to external",
      "Sophie repo import",
      "Gmail API",
      "SMS / telephony",
      "Function constructor",
      "eval(",
    ],
  },
  {
    fileSubstring: "jarvis-security-monitor-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "shell:true",
      "getUserMedia",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "fetch to external",
      "axios",
    ],
  },
  {
    fileSubstring: "jarvis-security-monitor-smoke.ts",
    patternNames: [
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "fetch to external",
    ],
  },
  {
    fileSubstring: "jarvis-security-monitor-simulation.ts",
    patternNames: [
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "fetch to external",
    ],
  },
  {
    fileSubstring: "jarvis-security-monitor-phase15-report.txt",
    patternNames: [
      "child_process",
      "exec(",
      "spawn(",
      "shell:true",
      "microphone",
      "camera access",
      "Robot / nut.js keyboard",
      "fetch to external",
      "Sophie repo import",
      "Gmail API",
      "SMS / telephony",
      "Function constructor",
      "eval(",
    ],
  },
  {
    fileSubstring: "JARVIS_MEMORY.md",
    patternNames: [
      "child_process",
      "exec(",
      "spawn(",
      "shell:true",
      "microphone",
      "camera access",
      "fetch to external",
      "Sophie repo import",
    ],
  },
  {
    fileSubstring: "JsonMemoryPersistence.ts",
    patternNames: ["fs writeFile"],
  },
  {
    fileSubstring: "MemoryValidator.ts",
    patternNames: [
      "child_process",
      "powershell",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
    ],
  },
  {
    fileSubstring: "jarvis-memory-audit.ts",
    patternNames: [
      "child_process",
      "exec(",
      "execSync(",
      "spawn(",
      "spawnSync(",
      "fork(",
      "shell:true",
      "getUserMedia",
      "camera access",
      "microphone",
      "Robot / nut.js keyboard",
      "fetch to external",
      "axios",
    ],
  },
  {
    fileSubstring: "jarvis-memory-smoke.ts",
    patternNames: [
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "fetch to external",
      "fs rm",
      "fs writeFile",
    ],
  },
  {
    fileSubstring: "jarvis-memory-simulation.ts",
    patternNames: [
      "microphone",
      "camera access",
      "child_process",
      "exec(",
      "spawn(",
      "fetch to external",
    ],
  },
  {
    fileSubstring: "jarvis-memory-phase16-report.txt",
    patternNames: [
      "child_process",
      "exec(",
      "spawn(",
      "shell:true",
      "microphone",
      "camera access",
      "Robot / nut.js keyboard",
      "fetch to external",
      "Sophie repo import",
      "Gmail API",
      "SMS / telephony",
      "Function constructor",
      "eval(",
    ],
  },
];

async function walk(dir: string): Promise<string[]> {
  const out: string[] = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === "node_modules" || entry.name === ".git" || entry.name === ".audit-cache") {
        continue;
      }
      out.push(...(await walk(full)));
    } else if (/\.(ts|tsx|js|mjs|cjs|md|txt)$/.test(entry.name)) {
      out.push(full);
    }
  }
  return out;
}

function isAllowlisted(filePath: string, patternName: string): boolean {
  const rel = path.relative(ROOT, filePath);
  for (const rule of ALLOWLIST) {
    if (rel.includes(rule.fileSubstring) && rule.patternNames.includes(patternName)) {
      return true;
    }
  }
  return false;
}

export interface InvariantReport {
  ok: boolean;
  scannedFiles: number;
  failures: string[];
}

export async function runSecurityInvariants(): Promise<InvariantReport> {
  const files: string[] = [];
  for (const d of SCAN_DIRS) {
    files.push(...(await walk(path.join(ROOT, d))));
  }
  // Also scan docs
  files.push(...(await walk(path.join(ROOT, "docs"))));

  const failures: string[] = [];

  for (const file of files) {
    const content = await fs.readFile(file, "utf8");
    const rel = path.relative(ROOT, file);

    for (const { name, pattern } of FORBIDDEN_PATTERNS) {
      if (isAllowlisted(file, name)) continue;
      if (pattern.test(content)) {
        failures.push(`${rel}: forbidden pattern "${name}"`);
      }
    }
  }

  // package.json: no runtime deps that imply network/LLM/shell
  const pkgPath = path.join(ROOT, "package.json");
  const pkg = JSON.parse(await fs.readFile(pkgPath, "utf8")) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };
  if (pkg.dependencies && Object.keys(pkg.dependencies).length > 0) {
    failures.push("package.json: Phase 1–2 must have zero runtime dependencies");
  }
  const forbiddenDeps = ["openai", "ollama", "axios", "node-fetch", "puppeteer", "playwright", "robotjs"];
  const allDeps = {
    ...pkg.dependencies,
    ...pkg.devDependencies,
  };
  for (const dep of forbiddenDeps) {
    if (allDeps[dep]) {
      failures.push(`package.json: forbidden dependency "${dep}"`);
    }
  }

  return {
    ok: failures.length === 0,
    scannedFiles: files.length,
    failures,
  };
}

// Allow direct execution
const isDirect =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (isDirect) {
  runSecurityInvariants().then((report) => {
    console.log(`Scanned ${report.scannedFiles} files`);
    if (report.ok) {
      console.log("All security invariants passed.");
    } else {
      console.error("Security invariant failures:");
      for (const f of report.failures) console.error(`  - ${f}`);
      process.exitCode = 1;
    }
  });
}
